#!/usr/bin/env python3
"""Patch the exported iOS Info.plist, which Godot writes fresh every export.

Run this after every iOS export and before archiving in Xcode. Editing the
plist by hand in Xcode does not stick: `ios/pixblast/pixblast-Info.plist` is
regenerated by the exporter, so the edit is silently lost on the next export
and the warnings come back.

Two fixes, both of which App Store validation complains about:

  * UIRequiresFullScreen -- deprecated in iOS 26 and ignored in a future
    release. It is also the reason an iPad ran the game in a compatibility
    window rather than full screen, so removing it is a fix, not just a
    warning silenced.

  * Empty NS*UsageDescription strings -- Godot writes the key whichever way
    the preset's privacy/*_usage_description is set, and an empty purpose
    string is rejected: "The value for NSCameraUsageDescription must be a
    non-empty string." The game uses no camera, microphone or photo library,
    so the honest fix is for the keys to be ABSENT rather than filled in with
    a purpose the app never has.

Idempotent: running it twice changes nothing the second time.

Run:  python3 tools/fix_ios_plist.py [path/to/Info.plist]
"""
import plistlib
import sys
from pathlib import Path

DEFAULT = Path(__file__).resolve().parent.parent / "ios" / "pixblast" / "pixblast-Info.plist"

# Deprecated in iOS 26. While present, iPadOS declines to give the app the
# whole screen.
DROP_ALWAYS = ["UIRequiresFullScreen"]

# Dropped only when empty. A non-empty one is a deliberate declaration and is
# left alone.
DROP_IF_EMPTY = [
    "NSCameraUsageDescription",
    "NSMicrophoneUsageDescription",
    "NSPhotoLibraryUsageDescription",
    "NSPhotoLibraryAddUsageDescription",
    "NSLocationWhenInUseUsageDescription",
    "NSContactsUsageDescription",
    "NSCalendarsUsageDescription",
    "NSBluetoothAlwaysUsageDescription",
]


def fix(path: Path) -> int:
    if not path.exists():
        print("  no plist at %s -- export first" % path)
        return 1
    with path.open("rb") as fh:
        plist = plistlib.load(fh)

    removed = []
    for key in DROP_ALWAYS:
        if key in plist:
            del plist[key]
            removed.append(key)
    for key in DROP_IF_EMPTY:
        if key in plist and not str(plist[key]).strip():
            del plist[key]
            removed.append("%s (was empty)" % key)

    if not removed:
        print("  %s already clean" % path.name)
        return 0

    with path.open("wb") as fh:
        plistlib.dump(plist, fh, sort_keys=False)
    for key in removed:
        print("  removed %s" % key)
    print("  %s patched" % path.name)
    return 0


if __name__ == "__main__":
    sys.exit(fix(Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT))
